### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] set position of the car as absolute
- [ ] add an event listener that targets the space button
- [ ] set an interval for every 16 millisecond and create function that moves the car forward a bit every interval
